### PR TITLE
win10 QEMULauncher.ini and ultibo.img

### PR DESCRIPTION
**Pull request by markfirmware**
This captures ultibo.img which should be replaced with a script for creating it, once that script is determined for win10. Mark.

### CODE REVIEW

**Comment by blippy** [comment]
Aargh! I'm (very) reluctant to add a 34M file to the project. Cloning it will be brutal.

That image file will be outdated quickly, too. 34M is the min size for a FAT32 filesystem. However, I think that Ultibo can read FAT12 systems, which can be between 34K (yes, KB), and 16M, which is a much better proposition. I could go down that route, and make an image available on Google Drive, or something.

A kernel would not need to go onto the image, as QEMU doesn't require it. 

fipq can _almost_ be run diskless, except for the matter of the core.4th words. I have a mechanism in place to obviate that.

I do like the idea of having QEMU use a disk, though. Firstly, I want to put a blocks file on it, so that people can load and save their own experiments dynamically. Secondly, I want to have user-configuration on it, to set up things like a keyboard. So a stock image mightn't be a good idea.

... on second thoughts, I've got an idea to work around this. 

Win 10 users could always install Cygwin, of course. That should give them the necessary tools to create images. It seems, according to https://ultibo.org/forum/viewtopic.php?f=4&t=624
that one can use a combo of qemu-img and Ultibo itself. There seem to be many options on there, and the devil is likely to be in the details.

Windows is not the ideal platform to develop on. It seems likely that one can get virtual file system mounters for Windows, given sufficient trawling of the internet. I do remember that I had an ext2 filesystem mounter for Win 7, for example.

In terms of simplicity for Windows users, I think the FAT12 option is a good way forward. I want to implement the blocks system first, so that I can put it on the file system and get it to do some "magic".

Am I right in thinking that QEMULauncher is actually a separate Ultibo tool in a separate repo?

**Comment by markfirmware** [comment]
A quick note - I am studying your comment.

I am also reluctant because it is more of a product than a source. Binary (non-textual) sources are still sources so binary isn't the issue with me, nor even the size.

By the way, the .git folder after cloning and checking out the branch is less than 400k and the expansion to 35MB is imperceptible on stretch/lite/3b+ I expect due to being mostly compressible zero bytes.

I used cygwin extensively some years ago and it certainly is a thorough system - however - git for windows is based on a next gen mingw that must be installed on win10 as a requirement to use github, and provides bash scripting and a bash window out of the box. I use that shell every minute I am on windows. Can the mingw part of git for windows be simply upgraded to provide the virtual file system manipulation tools? I don't know if it can have extra software added to it as easily as cygwin does. Also there are posts in the forum on some experiences making the virtual sd image for qemu.

Happy to have this pr for discussion and not merged. Mark.

**Comment by blippy** [comment]
The general rule of source control is that anything that gets generated shouldn't be under source control. 

Does mingw have dd and fdisk, because then you'd be in business. It would probably be easier for me just to make a small FAT12 file system and make it available.

**Comment by blippy** [comment]
I have created an ultibo.img file, and made it available here:
[ultibo.img](https://drive.google.com/file/d/1akRBnpphRVXvD3KEM4haf60TuW7arPoview?usp=sharing)
Download it and see if it works

**Pull request closed without merging**
